# Generated by Django 6.0.4 on 2026-05-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitoutline',
            name='release_as_vet',
            field=models.BooleanField(default=False, verbose_name='Release as VET'),
        ),
    ]
